name: Android CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Load Google Service File
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA | base64 -di > app/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run unit tests
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
