name: Android CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Create file google service
      run: cat /home/runner/work/InfoPlay/InfoPlay/app/google-services.json | base64
    - name: Putting Google Service
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/InfoPlay/InfoPlay/app/google-services.json
    - name: Write Admob file
      env:
        DATA: ${{ secrets.ADMOB_KEY }}
      run: echo $DATA > app/src/main/res/values/admob_id.xml | base64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with gradle
      run: ./gradlew build
